service: todo-serverless

provider:
  name: aws
  runtime: python3.8
  environment:
    TODO_TABLE: ${self:service}-table
functions:
  get_all_todos:
    handler: todos.get_all
    events:
      - httpApi:
            method: GET
            path: /todos
