service: todo-serverless

provider:
  name: aws
  runtime: python3.8
  environment:
    TODO_TABLE: ${self:service}
functions:
  helloWorld:
    handler: todo.get
    events:
      - httpApi:
            method: GET
            path: /todo
